### ISSUE TITLE
program start, data prep, join

### ISSUE THREAD

**Issue by lhmcgann** [ethanbwaite/csc369#1]
start the Scala program
read in both files
prune any unneeded columns (see input/data_description.md)
simplify the time_stamp (UNIX time) column to the point where an inner join yields most data
^ might run into issues with multiple combos

**Comment by lhmcgann** [comment]
change time stamp to day_of_week and hour(_minute?)

**Comment by zimeg** [comment]
pretty sure this is closed with [d0d715](https://github.com/ethanbwaite/csc369/commit/d0d715d5b259b203b6db58a98a2718ff77972d2c).

the timestamp is separated into the `DAY_OF_WEEK` and `HOUR` for ease of use. this can easily be modified later if we want to change it though – see `timestampToDayHour()`.

the ride and weather objects are basically entries in object form. nothing too special here.
